export const GET_SHOPPING_BASKET = "GET_SHOPPING_BASKET";
export const LOADING_SHOPPING_BASKET = "LOADING_SHOPPING_BASKET";
export const ERROR_SHOPPING_BASKET = "ERROR_SHOPPING_BASKET"

export const ADD_PURCHASE = 'ADD_PURCHASE';
export const DELETE_PURCHASE = 'DELETE_PURCHASE';
export const ERROR_PURCHASES = 'ERROR_PURCHASES';

export const GET_SEARCH_ITEMS = 'GET_SEARCH_ITEMS';

export const GET_ITEMS = 'GET_ITEMS';
export const LOADING_ITEMS = 'LOADING_ITEMS';
export const ERROR_ITEMS = 'ERROR_ITEMS';

export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';


